#!/usr/bin/env bash
# Idempotent install for the Link Shelf Cloud Agent environment.
#
# The app uses the Neon serverless HTTP driver (@neondatabase/serverless), which
# sends queries as HTTPS POSTs to https://<db-host>/sql instead of a TCP socket.
# In production that endpoint is Neon's cloud proxy. For local development we run:
#
#   Next.js  --(neon-http)-->  https://api.link-shelf.local/sql  (local proxy, :443)
#                                       |
#                                       +--(node-postgres)--> local Postgres :5432
#
# This lets the UNMODIFIED application talk to a fully local database. All of the
# work here lives in the environment layer only; no application code is changed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROXY_DIR="$REPO_ROOT/.cursor/neon-proxy"
CERT_DIR="/etc/neon-local-proxy"
DB_NAME="linkshelf"
DB_USER="shelf"
DB_PASS="shelf"
DB_HOST_ALIAS="db.link-shelf.local"
API_HOST_ALIAS="api.link-shelf.local"

echo "==> System packages (postgresql, client, openssl)"
if ! command -v psql >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq postgresql postgresql-client openssl
fi

echo "==> Start Postgres cluster"
sudo pg_ctlcluster "$(pg_lsclusters -h | awk 'NR==1{print $1}')" main start 2>/dev/null || \
  sudo service postgresql start 2>/dev/null || true

echo "==> Ensure role and database"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}';
  END IF;
END \$\$;
SQL
if ! sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
  sudo -u postgres createdb -O "${DB_USER}" "${DB_NAME}"
fi
sudo -u postgres psql -v ON_ERROR_STOP=1 -d "${DB_NAME}" \
  -c "GRANT ALL ON SCHEMA public TO ${DB_USER}; ALTER SCHEMA public OWNER TO ${DB_USER};"

echo "==> /etc/hosts aliases -> 127.0.0.1"
if ! grep -q "${API_HOST_ALIAS}" /etc/hosts; then
  echo "127.0.0.1 ${DB_HOST_ALIAS} ${API_HOST_ALIAS}" | sudo tee -a /etc/hosts >/dev/null
fi

echo "==> Self-signed cert for the local Neon proxy"
sudo mkdir -p "$CERT_DIR"
sudo chown "$USER" "$CERT_DIR"
if [ ! -f "$CERT_DIR/cert.pem" ]; then
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$CERT_DIR/key.pem" -out "$CERT_DIR/cert.pem" -days 3650 \
    -subj "/CN=link-shelf-local-db" \
    -addext "subjectAltName=DNS:${DB_HOST_ALIAS},DNS:${API_HOST_ALIAS},DNS:localhost,IP:127.0.0.1" \
    -addext "basicConstraints=critical,CA:TRUE"
  chmod 644 "$CERT_DIR/cert.pem"
  chmod 600 "$CERT_DIR/key.pem"
fi

echo "==> Allow node to bind privileged port 443"
NODE_BIN="$(readlink -f "$(command -v node)")"
sudo setcap 'cap_net_bind_service=+ep' "$NODE_BIN" || true

echo "==> Install dependencies (app + proxy)"
cd "$REPO_ROOT"
npm ci
cd "$PROXY_DIR"
npm install --no-audit --no-fund

echo "==> Apply database schema (idempotent)"
export PGPASSWORD="$DB_PASS"
DB_URL="postgres://${DB_USER}:${DB_PASS}@127.0.0.1:5432/${DB_NAME}"
if [ "$(psql "$DB_URL" -tAc "SELECT to_regclass('public.saves') IS NOT NULL")" != "t" ]; then
  psql -v ON_ERROR_STOP=1 "$DB_URL" -f "$REPO_ROOT/drizzle/0000_init.sql"
fi
for f in 0001_tag_sort_order 0002_daily_recommendations 0003_movie_watched; do
  psql -v ON_ERROR_STOP=1 "$DB_URL" -f "$REPO_ROOT/drizzle/${f}.sql"
done

echo "==> Write .env.local if missing"
cd "$REPO_ROOT"
if [ ! -f .env.local ]; then
  cat > .env.local <<EOF
# Generated by Cloud Agent env setup. DB -> local Neon HTTP proxy -> local Postgres.
DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@${DB_HOST_ALIAS}:5432/${DB_NAME}
HOUSEHOLD_PASSWORD=shelf-dev
HOUSEHOLD_SESSION_SECRET=$(openssl rand -hex 32)
CRON_SECRET=$(openssl rand -hex 16)
FOOD_TAG_SLUGS=recipes,recipe,cooking,food
MOVIE_TAG_SLUGS=movies,movie,films,film
# Optional integrations (app degrades gracefully when unset):
# TELEGRAM_BOT_TOKEN=
# TELEGRAM_WEBHOOK_SECRET=
# TELEGRAM_ALLOWED_USER_IDS=
# GEMINI_API_KEY=
EOF
fi

echo "==> Install complete"
